name: "Terraform CI/CD"

on:
  push:
    environment: staging
    branches:
      - master
  pull_request:
    environment: staging
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.environment }}
  cancel-in-progress: true

jobs:
  changes:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      vpc: ${{ steps.changes.outputs.vpc }}
      kube: ${{ steps.changes.outputs.kube }}
      kube_addons: ${{ steps.changes.outputs.kube_addons }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend: 'backend/*'
            vpc: 'vpc/*'
            kube: 'kube/*'
            kube_addons: 'kube/addons/*'
  conditions:
    name: "conditions"
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: "echo 'environment' ${{ inputs.environment }}"
  
  backend:
    needs: [changes]
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: backend
      nochange: ${{ needs.changes.outputs.backend == 'false' }}
      allow_tf: 'true'
      job_name: "Backend S3"
      environment: ${{ inputs.environment }}
    secrets: inherit

  vpc:
    needs: [changes, backend]
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: vpc
      #true true
      nochange: ${{ needs.changes.outputs.vpc == 'false' }}
      allow_tf: ${{ needs.backend.outputs.nochange == 'true' }}
      job_name: "VPC"
      environment: ${{ inputs.environment }}
    secrets: inherit

  kube:
    needs: [changes, backend, vpc]
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: kube
      #false true = false
      nochange: ${{ needs.changes.outputs.kube == 'false' }}
      allow_tf: ${{ needs.vpc.outputs.nochange == 'true' }}
      job_name: "Kubernetes"
      environment: ${{ inputs.environment }}
    secrets: inherit

  kube_addons:
    needs: [changes, backend, vpc, kube]
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: kube/addons
      #false false => false
      nochange: ${{ needs.changes.outputs.kube_addons == 'false' }}
      allow_tf: ${{ needs.kube.outputs.nochange == 'true' }}
      job_name: "Install helm addons"
      environment: ${{ inputs.environment }}
    secrets: inherit
