name: "Terraform CI/CD"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.environment }}
  cancel-in-progress: false

jobs:
  env:
    outputs:
      environment: |-
        ${{
           inputs.environment
        || github.ref_name == 'master' && 'production'
        || github.ref_name == 'dev'    && 'dev'
        ||                                'staging'
        }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
  changes:
    needs: [env]
    environment: ${{ needs.env.outputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      vpc: ${{ steps.changes.outputs.vpc }}
      kube: ${{ steps.changes.outputs.kube }}
      kube_addons: ${{ steps.changes.outputs.kube_addons }}
      nochange: |-
        ${{
          (
             steps.changes.outputs.backend == 'false'
          && steps.changes.outputs.vpc == 'false'
          && steps.changes.outputs.kube == 'false'
          && steps.changes.outputs.kube_addons == 'false'
          && 'true'
          )
        || 'false'
        }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend: 'backend/*'
            vpc: 'vpc/*'
            kube: 'kube/*'
            kube_addons: 'kube/addons/*'

  backend:
    if: ${{ needs.changes.outputs.nochange == 'false' }}
    needs: [changes, env]
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: backend
      nochange: ${{ needs.changes.outputs.backend == 'false' }}
      allow_tf: 'true'
      job_name: "Backend S3"
      environment: ${{ needs.env.outputs.environment }}
    secrets: inherit

  vpc:
    if: ${{ needs.changes.outputs.nochange == 'false' }}
    needs: [changes, env, backend]
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: vpc
      #true true
      nochange: ${{ needs.changes.outputs.vpc == 'false' }}
      allow_tf: ${{ needs.backend.outputs.nochange == 'true' }}
      job_name: "VPC"
      environment: ${{ needs.env.outputs.environment }}
    secrets: inherit

  kube:
    if: ${{ needs.changes.outputs.nochange == 'false' }}
    needs: [changes, env, vpc]
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: kube
      #false true = false
      nochange: ${{ needs.changes.outputs.kube == 'false' }}
      allow_tf: ${{ needs.vpc.outputs.nochange == 'true' }}
      job_name: "Kubernetes"
      environment: ${{ needs.env.outputs.environment }}
    secrets: inherit

  kube_addons:
    if: ${{ needs.changes.outputs.nochange == 'false' }}
    needs: [changes, env, kube]
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: kube/addons
      #false false => false
      nochange: ${{ needs.changes.outputs.kube_addons == 'false' }}
      allow_tf: ${{ needs.kube.outputs.nochange == 'true' }}
      job_name: "Install helm addons"
      environment: ${{ needs.env.outputs.environment }}
    secrets: inherit
