name: "Terraform CI/CD VPC"

on:
  push:
    branches:
      - master
    paths:
      - 'vpc/**'
  pull_request:
    branches:
      - master
    paths:
      - 'vpc/**'

jobs:
  terraform:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/terraform.yml
    with:
      working-directory: vpc
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_DYNAMODB: ${{ secrets.AWS_ENDPOINT_URL_DYNAMODB }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}