name: "Terraform CI/CD"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      vpc: ${{ steps.changes.outputs.vpc }}
      kube: ${{ steps.changes.outputs.kube }}
      kube_addons: ${{ steps.changes.outputs.kube_addons }}
    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend: 'backend/**'
            vpc: 'vpc/**'
            kube: 'kube/**'
            kube_addons: 'kube/addons/**'

  backend:
    needs: [changes]
    if: needs.changed.outputs.backend == 'true' || needs.changed.outputs.vpc == 'true' || needs.changed.outputs.kube == 'true' || needs.changed.outputs.kube_addons == 'true'
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: backend
      paths: 'backend/**'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_DYNAMODB: ${{ secrets.AWS_ENDPOINT_URL_DYNAMODB }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}

  vpc:
    needs: [changes, backend]
    if: needs.changed.outputs.vpc == 'true' || needs.changed.outputs.kube == 'true' || needs.changed.outputs.kube_addons == 'true'
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: vpc
      paths: 'vpc/**'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_DYNAMODB: ${{ secrets.AWS_ENDPOINT_URL_DYNAMODB }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}

  kube:
    needs: [changes, backend, vpc]
    if: needs.changed.outputs.kube == 'true' || needs.changed.outputs.kube_addons == 'true'
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: kube
      paths: 'kube/**'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_DYNAMODB: ${{ secrets.AWS_ENDPOINT_URL_DYNAMODB }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}

  kube_addons:
    needs: [changes, backend, vpc, kube]
    if: needs.changed.outputs.kube_addons == 'true'
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: kube/addons
      paths: 'kube/addons/**'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_DYNAMODB: ${{ secrets.AWS_ENDPOINT_URL_DYNAMODB }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
