name: "Terraform CI/CD kube addons"

on:
  push:
    branches:
      - master
    paths:
      - 'kube/addons/**'
  pull_request:
    branches:
      - master
    paths:
      - 'kube/addons/**'
  
  workflow_run:
    workflows: ['Terraform CI/CD kube']
    types:
      - completed
    branches: [master]

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      working-directory: kube/addons
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_DYNAMODB: ${{ secrets.AWS_ENDPOINT_URL_DYNAMODB }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}