name: "Terraform CI/CD"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  secrets:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_ENDPOINT_URL_DYNAMODB: ${{ secrets.AWS_ENDPOINT_URL_DYNAMODB }}
    YC_TOKEN: ${{ secrets.YC_TOKEN }}

jobs:
  changes:
    runs-on: ubuntu-latest
    uses: dorny/paths-filter@v3
    with:
      filters: |
        backend: 'backend/**'
        vpc: 'vpc/**'
        kube: 'kube/**'
        kube_addons: 'kube/addons/**'
  backend:
    needs: [changes]
    if: steps.changes.outputs.backend == 'true'
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: backend
      paths: 'backend/**'

  vpc:
    needs: [changes, backend]
    if: steps.changes.outputs.vpc == 'true'
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: vpc
      paths: 'vpc/**'

  kube:
    needs: [changes, backend, vpc]
    if: steps.changes.outputs.kube == 'true'
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: kube
      paths: 'kube/**'

  kube_addons:
    needs: [changes, backend, vpc, kube]
    if: steps.changes.outputs.kube_addons == 'true'
    uses: ./.github/workflows/_terraform.yml
    with:
      working-directory: kube/addons
      paths: 'kube/addons/**'
